server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://sh-cdb-ait73cfe.sql.tencentcdb.com:21411/gra_zlp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Zhoujie0420

---
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 10240MB

mybatis-plus:
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

sa-token:
  token-name: token
  is-print: false
