@startuml

actor Patient as P
actor Doctor as D

    usecase "视频问诊" as UC1
    usecase "问诊结果编辑" as UC2
    usecase "问诊结果查看" as UC3
    usecase "登录注册" as UC4

P --> UC1: 发起问诊
P --> UC3: 查看
P --> UC4: 登录注册


D --> UC2: 编辑
D --> UC4: 登录注册
D --> UC1: 发起问诊
D --> UC3: 查看




@enduml

